from enum import Enum

BACKGROUND_TYPE_MAP = {
    'ar_1_process': 'AR(1) Process',
    'random_walk': 'Random Walk',
    'sine_wave': 'Sine Wave',
    'poisson_moving_average': 'Poisson Moving Average'
}

class INDEPENDENT_ANOMALY_INJECTION_TYPE(Enum):
    SINGLE_ANOMALY_TYPE_SINGLE_DIMENSION = 1
    SINGLE_ANOMALY_TYPE_MULTIPLE_DIMENSION = 2
    MULTIPLE_ANOMALY_TYPE_SINGLE_DIMENSION = 3
    MULTIPLE_ANOMALY_TYPE_MULTIPLE_DIMENSION = 4

class CORRELATED_ANOMALY_INJECTION_TYPE(Enum):
    SINGLE_ANOMALY_TYPE_SINGLE_GROUP = 1
    SINGLE_ANOMALY_TYPE_MULTIPLE_GROUP = 2
    MULTIPLE_ANOMALY_TYPE_SINGLE_GROUP = 3
    MULTIPLE_ANOMALY_TYPE_MULTIPLE_GROUP = 4

class ANOMALY_TYPE(Enum):
    SPIKE = 1
    CORRELATED_SPIKE = 2
    DRIFT = 3
    CORRELATED_DRIFT = 4

BACKGROUND_TYPE_WITH_SUPPORTED_ANOMALY_TYPES = dict({
    'ar_1_process': [ANOMALY_TYPE.SPIKE, ANOMALY_TYPE.CORRELATED_SPIKE],
    'random_walk': [ANOMALY_TYPE.SPIKE, ANOMALY_TYPE.CORRELATED_SPIKE],
    'sine_wave': [ANOMALY_TYPE.SPIKE, ANOMALY_TYPE.CORRELATED_SPIKE, ANOMALY_TYPE.DRIFT, ANOMALY_TYPE.CORRELATED_DRIFT],
    'poisson_moving_average': [ANOMALY_TYPE.SPIKE, ANOMALY_TYPE.CORRELATED_SPIKE, ANOMALY_TYPE.DRIFT, ANOMALY_TYPE.CORRELATED_DRIFT]
})

BACKGROUND_TYPES_SUPPORTING_NORMAL_CORRELATION = ['ar_1_process', 'random_walk']